First homework
kraftn/java-lessons pull request #1
Opened 2019-03-30 16:32 UTC by kraftn

2019-03-31 13:15 UTC, 0v3rt1r3d commented on Main1.java
> +public class Main1 {
Назови классы попонятнее, типа `App.java` и `AppUsingLibrary.java`

2019-03-31 13:15 UTC, 0v3rt1r3d commented on Main1.java
> +public class Main1 {
Добавь package, типа `ru.kraftn.summator`. И package, это не просто строчка в начале файла. У тебя должна быть точно такая же структура директорий на диске

2019-03-31 13:15 UTC, 0v3rt1r3d commented on libs/Sum.java
> +    public static double plus(double a, double b){
Форматирование ctrl+alt+l, package

2019-03-31 13:15 UTC, 0v3rt1r3d commented on script1.bat
> +java Main1 %*
Скомпилированный файл будет лежать в той же директори, что и исходный. Не надо так. Создай директорию`src`, и положи исходные файлы по пакетам, `ru.package -> ru/package`, на уровне с `src` создай директорию `out`, в нее сразу отправляй скомпилированные файлы

2019-03-31 13:15 UTC, 0v3rt1r3d commented on script2.bat
> +cd ..
Огонь 👍 Но когда сделаешь отдельную папку под скомпилированные файлы и разбиение по пакетам, тут нужно будет добавить еще пару ключей компилятору

2019-04-06 18:47 UTC, kraftn commented
Переименовал файлы, отформатировал их содержимое и исправил структуру папок.

2019-04-07 14:06 UTC, 0v3rt1r3d requested changes

2019-04-07 14:06 UTC, 0v3rt1r3d commented on script2.bat
> +java -cp .\out;.\out\ru\kraftn\summator\libSum.jar ru.kraftn.appsummator.AppUsingLibrary %*
Здесь нет гарантии, что ты используешь `.class` библиотечного класса из `jar`, потому что он есть и в `jar`, и в `/out`. Раздели пожалуйста out-директории на `/out/app`  и `/out/lib`, и указывай компилятору туда складывать байт-код, или сделай явное удаление `Sum.class` после упаковки в `jar`

2019-04-12 08:43 UTC, 0v3rt1r3d approved these changes
Огонь. Было бы еще здорово переименовать `script1.bat` и `script2.bat` во что-то более говорящее, типа `build_app_with_library_and_run.bat`. Но это уже на твое усмотрение, можешь вливать

2019-04-12 09:23 UTC, merged